### PR TITLE
fix after upgraded slack plugin

### PR DESCRIPTION
**Pull request by matejsp**
fix for: https://github.com/jenkinsci/slack-plugin/issues/447

### CODE REVIEW

**Comment by ruediste** [comment]
I just checked out this commit and used it on our local Jenkins. Works like a charm :+1:

**Comment by matejsp** [comment]
updated PR, updated to slack plugin 2.10 
there was another api change (constructor)

**Comment by Marimoiro** [comment]
Thnak you for your PR .
I'm checking for it.

**Comment by timja** [comment]
A little worried about the patch here,
given that there's another issue https://github.com/jenkinsci/slack-plugin/issues/451
which requires another constructor change...

**Comment by timja** [comment]
hmm I guess if we make the current constructor not the databound one and move baseUrl it should be ok

**Comment by matejsp** [comment]
Yes, another not databound constructor should work.

**Comment by Marimoiro** [comment]
Test is complete.But it's 2am in Japan now.
So, I will merge next night.

**Comment by Marimoiro** [comment]
complete ヾ(*´ー`*)ﾉ Thank you.

**Pull request merged**
